// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyzpsxjuuobhizmdcoon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5enBzeGp1dW9iaGl6bWRjb29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjM2NDQsImV4cCI6MjA2NTgzOTY0NH0.3G-IPPTSMHkZuQIl8zBhrEeqBsNXYQ5jnWdwmZnn4wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);